schema:

- model_name: train_churn_dataset_v1
  description: Version 1 of Churn Prediction Training Dataset
  config:
    version: 1
    status: provisioning
  columns:
  - name: user_id
    tests:
    - unique
    - not_null
  - name: target_churn
    tests:
    - not_null
  - name: subscription_tier
    description: Auto-detected by Verity
  - name: signup_date
    description: Auto-detected by Verity
  - name: total_sessions
    description: Auto-detected by Verity
  - name: api_usage_count
    description: Auto-detected by Verity
  - name: region
    description: Auto-detected by Verity
  - name: avg_session_duration
    description: Auto-detected by Verity

- model_name: mon_prediction_drift
  description: Monitoring for prediction drift
  config:
    version: 1
    status: provisioning
  columns:
  - name: prediction_date
    tests:
    - not_null
  - name: avg_churn_prob
    tests:
    - not_null
  - name: min_churn_prob
    description: Auto-detected by Verity
  - name: model_id
    description: Auto-detected by Verity
  - name: max_churn_prob
    description: Auto-detected by Verity
  - name: prediction_count
    description: Auto-detected by Verity
