schema:
- model_name: train_churn_dataset
  description: This model is used to train the churn prediction to improve retention.
  config:
    materialized: table
    security_level: internal
    data_contract: false
    data_catalog: false
    version: 1
    status: provisioning
    latest: true
    governance:
      business_owner: super_marketing@example.com
      tech_owner: ml_engineering@example.com
  columns:
  - name: api_usage_count
    description: Auto-detected
  - name: subscription_tier
    description: Auto-detected
  - name: region
    description: Auto-detected
  - name: avg_session_duration
    description: Auto-detected
  - name: target_churn
    description: Auto-detected
  - name: total_sessions
    description: Auto-detected
  - name: user_id
    description: Auto-detected
    tests:
    - unique
    - not_null
  - name: signup_date
    description: Auto-detected
