schema:

- model_name: stg_users
  description: Raw user data with PII
  config:
    version: 1
    status: provisioning
  columns:
  - name: user_id
    tests:
    - unique
    - not_null
  - name: email
    description: User email address
    tests:
    - not_null
    policy: pii_masking
  - name: name
    description: User full name
    policy: pii_masking
  - name: region
    tests:
    - not_null
  - name: subscription_tier
    description: "User subscription level"
    tests:
    - not_null
  - name: signup_date
    description: "Date of user signup"
    tests:
    - not_null

- model_name: stg_activity
  description: User activity logs
  config:
    version: 1
    status: provisioning
  columns:
  - name: activity_id
    tests:
    - unique
    - not_null
  - name: user_id
    tests:
    - not_null
  - name: activity_type
    tests:
    - not_null
  - name: duration_sec
    description: Auto-detected by Verity
  - name: activity_at
    description: Auto-detected by Verity

- model_name: stg_model_metadata
  description: ML Model Registry
  config:
    version: 1
    status: provisioning
  columns:
  - name: model_id
    tests:
    - unique
    - not_null
  - name: version
    tests:
    - not_null
  - name: algorithm
    tests:
    - not_null
  - name: created_at
    description: Auto-detected by Verity
  - name: hyperparameters
    description: Auto-detected by Verity
  - name: created_by
    description: Auto-detected by Verity

- model_name: stg_predictions
  description: Model predictions log
  config:
    version: 1
    status: provisioning
  columns:
  - name: prediction_id
    tests:
    - unique
    - not_null
  - name: churn_probability
    description: Probability of churn (0-1)
    tests:
    - not_null
  - name: prediction_date
    description: Auto-detected by Verity
  - name: model_id
    description: Auto-detected by Verity
  - name: user_id
    description: Auto-detected by Verity
