schema:

- model_name: feat_user_engagement
  description: User engagement metrics for churn prediction
  config:
    version: 1
    status: provisioning
  columns:
  - name: user_id
    tests:
    - unique
    - not_null
  - name: total_sessions
    tests:
    - not_null
  - name: last_active_at
    description: Auto-detected by Verity
  - name: api_usage_count
    description: Auto-detected by Verity
  - name: avg_session_duration
    description: Auto-detected by Verity

- model_name: feat_user_demographics_masked
  description: Anonymized user demographics feature set
  config:
    version: 1
    status: provisioning
  columns:
  - name: user_id
    tests:
    - unique
    - not_null
  - name: email_hash
    description: Hashed email for joining without exposing PII
    tests:
    - not_null
  - name: subscription_tier
    description: Auto-detected by Verity
  - name: region
    description: Auto-detected by Verity
  - name: name_masked
    description: Auto-detected by Verity
  - name: signup_date
    description: Auto-detected by Verity
